"""configs/search/proxy-256x17-anchors.yaml: 28 anchors, resolved and checked.

A design file is written in RELATIVE terms and resolved against both a base
config and a study's declared space, and resolution both scales AND snaps -- a
categorical goes to its nearest declared choice, a float clamps into bounds, a
fixed axis collapses onto its singleton. Every one of those is silent, and
`example_anchors.yaml`'s own header records the case where it bit: a
`ridge_factor: 4.0` asking for 0.04, resolving to 0.03, and becoming a smaller
move than its author intended with nothing saying so.

So this file resolves all 28 against the REAL base and the REAL study space and
asserts what a structured design has to satisfy:

**Uniqueness twice over, EXCEPT inside a replicate set.** Distinct names
(`load_designs` enforces that) and distinct resolved points -- two anchors that
snap onto the same params by accident are one anchor run twice, and the study
would quietly have one fewer reference and a gap where a labelled factor should
be.

The five members of the `reference` group are the deliberate exception, and the
inversion is worth stating: they MUST resolve to byte-identical params, because
they differ only in `runtime.seed`, which is not a search parameter and therefore
is not in the params dict at all. So this file asserts uniqueness OUTSIDE the
group and identity WITHIN it, and asserts that they still reach distinct
`run_id`s -- which they do because `runtime.seed` is inside
`_scientific_payload(include_seed=True)`. Their spread in held-out loss is the
study's noise floor, so a design change that collapsed them would silently
replace a measured floor with zero.

**One factor at a time, verified AFTER resolution.** `rank-8` must differ from
`reference-k1` in `ska_rank` and nothing else. Checking the design file would
prove only that one FIELD was written; checking the resolved params proves no
second axis moved on the way through -- which is the failure that matters,
because `norm_clip_multiplier` and `n_ska_layers` are both derived from the base
and a factor on one can move the other.

**`reference-k1` IS the reference.** Not approximately: its resolved override set
must produce the same `run_id` as the base spec resolved directly. The run system
is content-addressed, so equal run_ids is the strongest available statement that
two configs are the same experiment -- and an anchor that merely resembles the
baseline is worse than none, because it looks like the reference and is not.

**The resolved table is a committed artifact.** `docs/proxy-256x17-anchors-
resolved.md`, regenerated by `scripts/resolve_anchor_design.py` and diffed here,
so snapping cannot stay hidden in a function nobody runs.
"""
from __future__ import annotations

import pathlib
import subprocess
import sys

import pytest

REPO = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

pytestmark = pytest.mark.correctness

STUDY = REPO / "configs/search/proxy-256x17-interactions-v1.yaml"
DESIGNS = REPO / "configs/search/proxy-256x17-anchors.yaml"
ARTIFACT = REPO / "docs/proxy-256x17-anchors-resolved.md"

EXPECTED_ANCHORS = 28

#: The replicate set: one configuration, five training seeds, and the ONLY group
#: of anchors permitted to resolve onto the same params. Their spread in held-out
#: loss is the study's noise floor.
REPLICATES = ("reference-k1", "reference-seed-43", "reference-seed-44",
              "reference-seed-45", "reference-seed-46")
EXPECTED_SEEDS = (42, 43, 44, 45, 46)

#: name -> the ONE resolved param key it is allowed to move away from
#: `reference-k1`. `None` marks the reference itself; a tuple marks the three
#: deliberate two-factor cells.
ONE_FACTOR = {
    "reference-k1": (),
    # The seed repeats move NO param, by construction: the seed is not a search
    # axis, so it does not appear in a params dict. They are listed here so the
    # one-factor sweep below covers them -- an empty tuple is the strongest
    # statement available, and it is exactly what a replicate has to satisfy.
    "reference-seed-43": (),
    "reference-seed-44": (),
    "reference-seed-45": (),
    "reference-seed-46": (),
    "rank-8": ("ska_rank",),
    "rank-16": ("ska_rank",),
    "rank-32": ("ska_rank",),
    "layers-2": ("n_ska_layers",),
    "layers-3": ("n_ska_layers",),
    "layers-6": ("n_ska_layers",),
    "layers-8": ("n_ska_layers",),
    "placement-even": ("placement",),
    "placement-midlate": ("placement",),
    "placement-late": ("placement",),
    "ridge-low": ("ska_ridge",),
    "ridge-high": ("ska_ridge",),
    "layerscale-low": ("ska_layerscale_init",),
    "layerscale-high": ("ska_layerscale_init",),
    "normclip-low": ("norm_clip_multiplier",),
    "normclip-high": ("norm_clip_multiplier",),
    "gamma-low": ("gamma_value",),
    "gamma-high": ("gamma_value",),
    "reference-k2": ("ska_power_K",),
    "lr-low": ("learning_rate",),
    "lr-high": ("learning_rate",),
    # The only two-factor cells in the set, and deliberately so: see the design
    # file's header for why K x ridge is the one interaction the anchors estimate
    # themselves rather than leaving to the sampler.
    "k2-ridge-low": ("ska_power_K", "ska_ridge"),
    "k2-ridge-high": ("ska_power_K", "ska_ridge"),
}

#: The exact values every one-factor anchor is expected to resolve TO. Written
#: out rather than recomputed from the factors, because recomputing the factor
#: arithmetic in the test would make the test agree with a bug in the resolution
#: by construction.
EXPECTED_VALUE = {
    "rank-8": 8, "rank-16": 16, "rank-32": 32,
    "layers-2": 2, "layers-3": 3, "layers-6": 6, "layers-8": 8,
    "placement-even": "even", "placement-midlate": "midlate",
    "placement-late": "late",
    "ridge-low": 0.003, "ridge-high": 0.03,
    "layerscale-low": 0.002, "layerscale-high": 0.03,
    "normclip-low": 0.75, "normclip-high": 1.25,
    "gamma-low": 0.90, "gamma-high": 1.05,
    "reference-k2": 2,
    "lr-low": 0.00032, "lr-high": 0.00048,
}


@pytest.fixture(scope="module")
def resolved():
    """(study_spec, base_sections, base_model, space, base_lr, rows)."""
    sys.path.insert(0, str(REPO / "scripts"))
    from resolve_anchor_design import resolve_all
    return resolve_all(STUDY)


@pytest.fixture(scope="module")
def by_name(resolved):
    return {design.name: params for design, params, _ in resolved[5]}


@pytest.fixture(scope="module")
def overrides_by_name(resolved):
    return {design.name: overrides for design, _, overrides in resolved[5]}


# ------------------------------------------------------------------ the set ----

def test_there_are_exactly_twenty_eight(resolved):
    assert len(resolved[5]) == EXPECTED_ANCHORS


def test_the_names_are_the_ones_this_file_reasons_about(by_name):
    """Guards every parametrised assertion below: a renamed anchor would
    otherwise silently drop out of the one-factor check."""
    assert set(by_name) == set(ONE_FACTOR)


def test_every_name_is_unique():
    """`load_designs` raises on a duplicate, so this asserts the loader ran."""
    from experimentation.sweep.search.anchors import load_designs

    designs = load_designs(DESIGNS, minimum=EXPECTED_ANCHORS)
    assert len({d.name for d in designs}) == len(designs) == EXPECTED_ANCHORS


def test_every_resolved_point_outside_the_replicate_set_is_unique(by_name):
    """The failure this prevents: two anchors on one point spend two of the
    study's 256 trials answering one question, so the study has one fewer
    reference and a gap where a labelled factor should be -- and the gap is
    invisible in the output."""
    seen = {}
    for name, params in sorted(by_name.items()):
        if name in REPLICATES:
            continue
        key = tuple(sorted((k, repr(v)) for k, v in params.items()))
        assert key not in seen, (
            f"{name!r} resolves to the same point as {seen[key]!r}; two trials "
            f"would be spent on one question")
        seen[key] = name
    # `reference-k1` is itself a member of the replicate set, so all five are
    # skipped and 23 distinct non-reference points remain.
    assert len(seen) == EXPECTED_ANCHORS - len(REPLICATES) == 23


def test_the_replicate_set_resolves_to_ONE_point(by_name):
    """The inversion, and it is the property that makes the noise floor a
    controlled measurement: five designs, one params dict. Anything else means a
    factor moved and the group is measuring that factor, not the seed."""
    keys = {tuple(sorted((k, repr(v)) for k, v in by_name[name].items()))
            for name in REPLICATES}
    assert len(keys) == 1, (
        "the reference replicates do NOT resolve to one point, so their spread "
        "is not a noise floor -- it is that factor's effect, mislabelled")


def test_every_anchor_has_a_distinct_run_id(resolved, overrides_by_name):
    """The stronger statement, in the run system's own vocabulary: distinct
    run_ids means distinct run directories, so no two anchors collide on disk.

    Holds for the replicate set too, and that is the whole reason the seed is a
    legitimate way to spell a repeat: `runtime.seed` is inside
    `_scientific_payload(include_seed=True)`, so five identical param dicts at
    five seeds are five runs. If it were outside, the five would share a
    directory and four of them would be lost.
    """
    sys.path.insert(0, str(REPO / "scripts"))
    from resolve_anchor_design import _designated_seed, _identity

    study_spec, base_sections = resolved[0], resolved[1]
    designs = {d.name: d for d, _, _ in resolved[5]}
    ids = {}
    for name, overrides in sorted(overrides_by_name.items()):
        identity = _identity(study_spec, base_sections, overrides,
                             seed=_designated_seed(designs[name]))
        assert "run_id" in identity, f"{name}: {identity}"
        assert identity["run_id"] not in ids, (
            f"{name} and {ids[identity['run_id']]} share run_id "
            f"{identity['run_id']}")
        ids[identity["run_id"]] = name
    assert len(ids) == EXPECTED_ANCHORS


def test_the_replicate_set_shares_one_group_id(resolved, overrides_by_name):
    """`group_id` excludes the seed, so the run system already spells "one
    experiment, five datapoints" -- which is what lets `results.py` group them
    without being told to."""
    sys.path.insert(0, str(REPO / "scripts"))
    from resolve_anchor_design import _designated_seed, _identity

    study_spec, base_sections = resolved[0], resolved[1]
    designs = {d.name: d for d, _, _ in resolved[5]}
    identities = [_identity(study_spec, base_sections, overrides_by_name[name],
                            seed=_designated_seed(designs[name]))
                  for name in REPLICATES]
    assert len({i["group_id"] for i in identities}) == 1
    assert sorted(i["seed"] for i in identities) == list(EXPECTED_SEEDS)


def test_the_replicate_seeds_are_the_ones_the_design_file_declares(resolved):
    """Pinned so a silent edit that dropped a member -- or duplicated a seed --
    fails here rather than producing a smaller or degenerate noise floor."""
    from experimentation.sweep.search.anchors import (
        check_replicates_resolve, reference_groups, resolved_seed)

    base_seed = int(resolved[1]["runtime"]["seed"])
    designs = [d for d, _, _ in resolved[5]]
    groups = reference_groups(designs)
    assert sorted(groups) == ["reference"]
    assert sorted(d.name for d in groups["reference"]) == sorted(REPLICATES)
    assert sorted(resolved_seed(d, base_seed)
                  for d in groups["reference"]) == list(EXPECTED_SEEDS)
    check_replicates_resolve(designs, base_seed)


# --------------------------------------------------------- the reference point ----

def test_reference_k1_reproduces_the_base_spec_exactly(resolved,
                                                       overrides_by_name):
    """Content-addressed identity is the strongest available statement that two
    configs are the same experiment. An anchor that merely RESEMBLES the baseline
    is worse than none: it looks like the reference and is not."""
    sys.path.insert(0, str(REPO / "scripts"))
    from resolve_anchor_design import _identity
    from experimentation.run.resolve import resolve_run_spec
    from experimentation.run.spec import group_id, run_id

    base = resolve_run_spec(REPO / "configs/runs/proxy-256x17.yaml")
    identity = _identity(resolved[0], resolved[1],
                         overrides_by_name["reference-k1"])
    assert identity["run_id"] == run_id(base)
    assert identity["group_id"] == group_id(base)


def test_reference_k1_sets_no_scientific_factor(resolved):
    """It has to be the all-defaults design, or it is a reference by coincidence
    rather than by construction.

    `reference_group` is exempt and `seed` is not: the group name is BOOKKEEPING
    (it says which replicate set this trial belongs to and changes no input),
    while a seed WOULD change the experiment -- so `reference-k1` must keep
    inheriting the base spec's own seed, which is what makes it the member a
    reader can check against `configs/runs/proxy-256x17.yaml` by eye.
    """
    import dataclasses

    from experimentation.sweep.search.anchors import Design

    design = next(d for d, _, _ in resolved[5] if d.name == "reference-k1")
    for field in dataclasses.fields(Design):
        if field.name in ("name", "reference_group"):
            continue
        assert getattr(design, field.name) == field.default, field.name
    assert design.reference_group == "reference"
    assert design.seed == "baseline"


# ---------------------------------------------------------- one factor at a time ----

@pytest.mark.parametrize("name", sorted(set(ONE_FACTOR) - {"reference-k1"}))
def test_each_anchor_moves_only_its_named_factor(name, by_name):
    reference = by_name["reference-k1"]
    params = by_name[name]
    moved = sorted(k for k in reference if params[k] != reference[k])
    assert moved == sorted(ONE_FACTOR[name]), (
        f"{name} moved {moved}; its name claims {sorted(ONE_FACTOR[name])}. "
        f"A design whose params deny its name is the one failure a labelled "
        f"design set exists to prevent.")


@pytest.mark.parametrize("name", sorted(EXPECTED_VALUE))
def test_each_one_factor_anchor_reaches_its_intended_value(name, by_name):
    """The factors are relative, so the resolved value is factor x base clamped
    into the space. These are the values that arithmetic is supposed to land on;
    if a factor were chosen without checking the bounds it would land short and
    this is what would say so."""
    axis = ONE_FACTOR[name][0]
    assert by_name[name][axis] == EXPECTED_VALUE[name]


def test_the_two_factor_cells_complete_a_two_by_two(by_name):
    """`reference-k2` + `ridge-low`/`ridge-high` + `k2-ridge-low`/`k2-ridge-high`
    plus the reference is a complete 2x2 over (K, ridge extreme)."""
    cells = {(by_name[n]["ska_power_K"], by_name[n]["ska_ridge"])
             for n in ("ridge-low", "ridge-high", "k2-ridge-low",
                       "k2-ridge-high")}
    assert cells == {(1, 0.003), (1, 0.03), (2, 0.003), (2, 0.03)}


# --------------------------------------------------- fixed axes and snapping ----

@pytest.mark.parametrize("axis,value", [("weight_decay", 0.1),
                                        ("warmup_ratio", 0.04),
                                        ("grad_clip", 1.0)])
def test_every_anchor_lands_on_the_studys_fixed_values(axis, value, by_name):
    """An anchor cannot disagree with the study about a pinned parameter. Note
    that `Design.warmup_ratio` DEFAULTS to 0.02, so this is the fixed singleton
    doing real work rather than a coincidence -- see the snapping section of the
    committed artifact."""
    for name, params in by_name.items():
        assert params[axis] == value, f"{name}: {axis}={params[axis]}"


def test_the_warmup_snap_is_real_and_recorded(resolved, by_name):
    """Guards the guard above: if Design's default ever becomes 0.04 the previous
    test would pass for the wrong reason."""
    design = next(d for d, _, _ in resolved[5] if d.name == "reference-k1")
    assert design.warmup_ratio == 0.02, (
        "Design.warmup_ratio no longer defaults to 0.02, so the fixed-axis snap "
        "is no longer being exercised -- update the artifact's snapping section")
    assert by_name["reference-k1"]["warmup_ratio"] == 0.04


def test_every_anchor_supplies_every_required_parameter(by_name):
    from experimentation.sweep.search.space import REQUIRED_PARAMS

    for name, params in by_name.items():
        missing = sorted(set(REQUIRED_PARAMS) - set(params))
        assert not missing, f"{name} is missing {missing}"


# -------------------------------------------------------- parameter-count spread ----

def test_the_design_spans_a_real_parameter_range(resolved, overrides_by_name):
    """The anchors are what tell a reader whether the loss/parameter Pareto front
    has anything to be a front OVER. If every anchor had the same count the
    Pareto table would be a ranking with extra columns."""
    sys.path.insert(0, str(REPO / "scripts"))
    from resolve_anchor_design import _identity

    counts = {name: _identity(resolved[0], resolved[1], o)["param_count"]
              for name, o in overrides_by_name.items()}
    assert min(counts.values()) < 25_000_000 < max(counts.values())
    spread = max(counts.values()) / min(counts.values()) - 1.0
    assert spread > 0.04, f"only a {spread:.1%} parameter spread: {counts}"


# ------------------------------------------------------------- the artifact ----

def test_the_resolved_design_artifact_is_committed_and_current():
    """The readable name -> resolved-parameters table, diffed against its
    generator. Committed so that snapping is visible in review rather than only
    to whoever runs the script."""
    sys.path.insert(0, str(REPO / "scripts"))
    from resolve_anchor_design import render_markdown, resolve_all

    assert ARTIFACT.is_file(), (
        f"{ARTIFACT.relative_to(REPO)} is missing. Regenerate with:\n"
        f"  python scripts/resolve_anchor_design.py "
        f"{STUDY.relative_to(REPO)} > {ARTIFACT.relative_to(REPO)}")
    expected = render_markdown(*resolve_all(STUDY))
    assert ARTIFACT.read_text() == expected, (
        "the committed artifact is stale. Regenerate with:\n"
        f"  python scripts/resolve_anchor_design.py "
        f"{STUDY.relative_to(REPO)} > {ARTIFACT.relative_to(REPO)}")


def test_the_generator_runs_as_a_command():
    """It is documented as a command, so it has to work as one -- a script whose
    only caller is a test is a function with a shebang."""
    result = subprocess.run(
        [sys.executable, str(REPO / "scripts/resolve_anchor_design.py"),
         str(STUDY), "--format=json"],
        capture_output=True, text=True, cwd=REPO)
    assert result.returncode == 0, result.stderr[-2000:]
    import json
    payload = json.loads(result.stdout)
    assert len(payload["anchors"]) == EXPECTED_ANCHORS
