"""Pin run identity: config_hash / group_id / run_id / sweep_id.

These four values name every run directory, group replicates, and stamp every
checkpoint (train.py writes cfg_hash into each checkpoint's meta). If a refactor
changes any of them, completed science is silently renamed: re-deriving a
finished run's id from its own spec yields a different directory, and its
checkpoint's stored cfg_hash stops matching a freshly-loaded config.

The expected values in code-tests/identity_baseline.json were generated by
scripts/gen_identity_baseline.py BEFORE the koopman_lm/experimentation package
split, and committed first. That ordering is the point -- a pin written after a
refactor records whatever the refactored code produces, which proves nothing.

If this test fails, the refactor you just made was not identity-preserving.
Regenerate the baseline ONLY when an intentional change to run identity has been
decided and the old->new mapping recorded -- never to make this go green.
"""
import json
from pathlib import Path

import pytest

pytestmark = pytest.mark.correctness

REPO_ROOT = Path(__file__).resolve().parent.parent
BASELINE_PATH = Path(__file__).parent / "identity_baseline.json"
BASELINE = json.loads(BASELINE_PATH.read_text())


def test_config_hash_unchanged_for_every_registry_config():
    from koopman_lm.config import CONFIG_REGISTRY, build_config, config_hash

    expected = BASELINE["config_hash"]
    assert set(expected) == set(CONFIG_REGISTRY), (
        "the config registry gained or lost entries; regenerate the baseline "
        "deliberately if that was intended")
    actual = {n: config_hash(build_config(n)) for n in CONFIG_REGISTRY}
    assert actual == expected


@pytest.mark.parametrize("rel", sorted(BASELINE["run_spec"]))
def test_run_spec_identity_unchanged(rel):
    from koopman_lm.config import config_hash
    from koopman_lm.run.resolve import resolve_run_spec
    from koopman_lm.run.spec import group_id, run_id

    spec = resolve_run_spec(REPO_ROOT / rel)
    assert {
        "config_hash": config_hash(spec.model),
        "group_id": group_id(spec),
        "run_id": run_id(spec),
    } == BASELINE["run_spec"][rel]


@pytest.mark.parametrize("rel", sorted(BASELINE["sweep"]))
def test_sweep_identity_and_cell_expansion_unchanged(rel):
    """Covers the sweep grid too: a cell's run_id encodes which axis values it
    got, so this catches a regression in expand_cells' override application as
    well as one in the hash itself."""
    from koopman_lm.run.spec import group_id, run_id
    from koopman_lm.sweep.spec import expand_cells, load_sweep_spec, sweep_id

    expected = BASELINE["sweep"][rel]
    sweep = load_sweep_spec(REPO_ROOT / rel)
    cells = expand_cells(sweep)

    assert sweep_id(sweep) == expected["sweep_id"]
    assert len(cells) == expected["n_cells"]
    assert [
        {
            "overrides": {k: str(v) for k, v in sorted(c.overrides.items())},
            "group_id": group_id(c.spec),
            "run_id": run_id(c.spec),
        }
        for c in cells
    ] == expected["cells"]


def test_baseline_file_is_in_sync_with_its_generator():
    """The generator and the committed artifact must not drift: if someone edits
    identity_baseline.json by hand, or changes the generator's spec list without
    regenerating, this catches it."""
    import subprocess
    import sys

    result = subprocess.run(
        [sys.executable, str(REPO_ROOT / "scripts" / "gen_identity_baseline.py")],
        capture_output=True, text=True, cwd=REPO_ROOT, check=True)
    assert json.loads(result.stdout) == BASELINE
