# -*- coding: utf-8 -*-
"""SKA_v9_Tool_Calling_LM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HM1-IVsoQjLPKHtboynY3y9HFP_TUeZI

# SKA v9: Scaled Koopman Attention — 8M Param Tool-Calling LM

**Single Colab notebook.** Run all cells on A100.

## Architecture
- Mamba-3 backbone + Spectral Koopman Attention (SKA)
- ~8M parameters with BPE tokenizer (8K vocab)
- Triton-fused RoPE, parallel prefix scan, CG lift

## Benchmark
- Pretrained on ToolAlpaca (real tool-call traces)
- Evaluated on function name + argument accuracy
- Compared against published BFCL scores (Kimi, Qwen, etc.)

## 1. Setup & Dependencies
"""

!pip install -q torch triton sentencepiece datasets tokenizers matplotlib numpy tqdm transformers accelerate

"""## 1. Setup & Dependencies"""

# fmt: off
INSTALL_CMD = """
pip install -q torch triton sentencepiece datasets tokenizers \
    matplotlib numpy tqdm transformers accelerate
"""

def run_setup():
    """Run this in Colab's first cell."""
    import subprocess, sys
    subprocess.check_call(sys.executable.split() + ["-m"] + INSTALL_CMD.strip().split()[1:])

# Uncomment in Colab:
# run_setup()

import math, time, random, os, sys, warnings, string, json, re
from dataclasses import dataclass, field
from typing import Optional, List, Tuple, Dict, Any
from collections import Counter, defaultdict
from contextlib import nullcontext

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import numpy as np
from tqdm.auto import tqdm

# AMP setup
try:
    from torch.amp import GradScaler
    def amp_autocast(device_type='cuda'):
        return torch.amp.autocast(device_type, dtype=torch.bfloat16)
    def amp_scaler():
        return GradScaler(device_type='cuda')
    HAS_AMP = True
except (ImportError, TypeError):
    HAS_AMP = False
    def amp_autocast(device_type='cuda'):
        return nullcontext()
    def amp_scaler():
        return None

# Triton import
try:
    import triton
    import triton.language as tl
    HAS_TRITON = True
except ImportError:
    HAS_TRITON = False
    print("WARNING: Triton not available, falling back to PyTorch ops")

try:
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    HAS_MATPLOTLIB = True
except ImportError:
    HAS_MATPLOTLIB = False

warnings.filterwarnings('ignore', category=UserWarning)
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(f"Device: {DEVICE}")
if torch.cuda.is_available():
    props = torch.cuda.get_device_properties(0)
    mem = getattr(props, 'total_mem', None) or getattr(props, 'total_memory', 0)
    print(f"GPU: {props.name} | Memory: {mem / 1e9:.1f} GB")
    print(f"Triton: {'available' if HAS_TRITON else 'NOT available'}")
    print(f"AMP: {'bfloat16' if HAS_AMP else 'disabled'}")

"""## 2. Triton Kernels"""

# ---------- Kernel 1: Fused RoPE + Cumulative Angle ----------
# Standard RoPE does 3 ops: cumsum(delta*omega) -> cos/sin -> rotate
# We fuse all three into one kernel. For sequence length T and head dim N,
# this eliminates 2 intermediate buffers and 2 kernel launches.

if HAS_TRITON:
    @triton.jit
    def _fused_rope_kernel(
        # Input: keys or queries, shape (B*H, T, N) row-major
        X_ptr, stride_xb, stride_xt, stride_xn,
        # Output: rotated, same shape
        OUT_ptr, stride_ob, stride_ot, stride_on,
        # Delta: (B*H, T) — step sizes
        DELTA_ptr, stride_db, stride_dt,
        # Omega: (N_half,) — base frequencies
        OMEGA_ptr,
        # Dimensions
        T: tl.constexpr, N_HALF: tl.constexpr,
        BLOCK_T: tl.constexpr, BLOCK_N: tl.constexpr,
    ):
        """Fused cumulative-angle RoPE rotation.

        For each (batch*head, n_half) pair:
          theta[t, n] = sum_{s=0}^{t} delta[s] * omega[n]
          out[t, 2n]   = x[t, 2n]*cos(theta) - x[t, 2n+1]*sin(theta)
          out[t, 2n+1] = x[t, 2n]*sin(theta) + x[t, 2n+1]*cos(theta)

        The cumulative sum over T is done via sequential scan within each
        program instance (T dimension). This is fine because the scan is
        over the time dimension within a single (batch, head, freq) slice,
        and we parallelize across batch*head and freq dimensions.
        """
        pid_b = tl.program_id(0)   # batch*head index
        pid_n = tl.program_id(1)   # frequency pair index (over N_HALF)

        n_off = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)  # freq indices
        n_mask = n_off < N_HALF

        # Load omega for this freq block
        omega = tl.load(OMEGA_ptr + n_off, mask=n_mask, other=0.0)

        # Sequential scan over time for cumulative angle
        theta_acc = tl.zeros((BLOCK_N,), dtype=tl.float32)

        for t in range(T):
            # Load delta[b, t]
            delta = tl.load(DELTA_ptr + pid_b * stride_db + t * stride_dt)
            theta_acc += delta * omega

            cos_t = tl.cos(theta_acc)
            sin_t = tl.sin(theta_acc)

            # Load even/odd components
            x_even_ptr = X_ptr + pid_b * stride_xb + t * stride_xt + 2 * n_off * stride_xn
            x_odd_ptr = X_ptr + pid_b * stride_xb + t * stride_xt + (2 * n_off + 1) * stride_xn

            x_e = tl.load(x_even_ptr, mask=n_mask, other=0.0).to(tl.float32)
            x_o = tl.load(x_odd_ptr, mask=n_mask, other=0.0).to(tl.float32)

            # Rotate
            out_e = x_e * cos_t - x_o * sin_t
            out_o = x_e * sin_t + x_o * cos_t

            # Store
            o_even_ptr = OUT_ptr + pid_b * stride_ob + t * stride_ot + 2 * n_off * stride_on
            o_odd_ptr = OUT_ptr + pid_b * stride_ob + t * stride_ot + (2 * n_off + 1) * stride_on

            tl.store(o_even_ptr, out_e.to(tl.float16), mask=n_mask)
            tl.store(o_odd_ptr, out_o.to(tl.float16), mask=n_mask)


    def fused_rope(x, delta, omega):
        """
        Fused RoPE rotation.

        Args:
            x: (B, T, H, N) — input keys/queries (interleaved real/imag)
            delta: (B, T, H) — step sizes
            omega: (H, N_half) — base frequencies

        Returns:
            rotated: (B, T, H, N) — RoPE-rotated output
        """
        B, T, H, N = x.shape
        N_HALF = N // 2

        # Reshape to (B*H, T, N) for kernel
        x_flat = x.permute(0, 2, 1, 3).contiguous().reshape(B * H, T, N)
        delta_flat = delta.permute(0, 2, 1).contiguous().reshape(B * H, T)

        # Expand omega from (H, N_half) to (B*H, N_half) isn't needed;
        # each program indexes into omega by freq, omega is shared
        # But we need per-head omega. Tile it.
        omega_flat = omega.contiguous()  # (H, N_half)
        # We'll pass omega per-head by indexing pid_b % H... actually simpler
        # to just expand to (B*H, N_half) and index by pid_b
        omega_expanded = omega_flat.unsqueeze(0).expand(B, -1, -1).reshape(B * H, N_HALF)

        out_flat = torch.empty_like(x_flat)

        BLOCK_N = min(triton.next_power_of_2(N_HALF), 64)

        grid = (B * H, triton.cdiv(N_HALF, BLOCK_N))

        # We need omega per program — pass the expanded version and index by pid_b
        # Actually we need a 2D omega. Let's simplify: use a wrapper kernel.
        # For now, use the simpler approach: one kernel per (b*h), scan over T.
        # The parallelism is across B*H*ceil(N_HALF/BLOCK_N) programs.

        _fused_rope_kernel[grid](
            x_flat, x_flat.stride(0), x_flat.stride(1), x_flat.stride(2),
            out_flat, out_flat.stride(0), out_flat.stride(1), out_flat.stride(2),
            delta_flat, delta_flat.stride(0), delta_flat.stride(1),
            omega_expanded,  # each pid_b reads omega_expanded[pid_b, :]
            T=T, N_HALF=N_HALF, BLOCK_T=1, BLOCK_N=BLOCK_N,
        )

        return out_flat.reshape(B, H, T, N).permute(0, 2, 1, 3)


    # ---------- Kernel 2: Parallel Prefix Scan (Blelloch) ----------
    # Replaces the serial `for c in range(n_chunks)` inter-chunk propagation.
    # Each chunk state = decay * prev_state + chunk_contribution.
    # This is a linear recurrence: s[c] = a[c]*s[c-1] + b[c]
    # which is a prefix scan with the operator (a, b) ⊕ (a', b') = (a*a', a'*b + b').

    @triton.jit
    def _prefix_scan_kernel(
        # Decay per chunk: (B*H, n_chunks) — log-space
        LOG_DECAY_ptr, stride_lb, stride_lc,
        # Chunk contributions: (B*H, n_chunks, NP)
        CONTRIB_ptr, stride_cb, stride_cc, stride_cn,
        # Output states: (B*H, n_chunks, NP)
        OUT_ptr, stride_ob, stride_oc, stride_on,
        # Dimensions
        N_CHUNKS: tl.constexpr, NP: tl.constexpr,
        BLOCK_NP: tl.constexpr,
    ):
        """Inclusive prefix scan for linear recurrence s[c] = exp(d[c])*s[c-1] + b[c].

        Uses sequential scan within each (batch*head, state_block) program.
        Parallelism is across B*H and state dimension blocks.
        For typical n_chunks=16-64 the sequential scan is fast.
        """
        pid_b = tl.program_id(0)  # batch*head
        pid_s = tl.program_id(1)  # state block

        s_off = pid_s * BLOCK_NP + tl.arange(0, BLOCK_NP)
        s_mask = s_off < NP

        # Running state accumulator
        state = tl.zeros((BLOCK_NP,), dtype=tl.float32)

        for c in range(N_CHUNKS):
            # Load log_decay and contribution
            log_d = tl.load(LOG_DECAY_ptr + pid_b * stride_lb + c * stride_lc)
            decay = tl.exp(log_d)

            contrib = tl.load(
                CONTRIB_ptr + pid_b * stride_cb + c * stride_cc + s_off * stride_cn,
                mask=s_mask, other=0.0
            )

            state = decay * state + contrib

            # Store
            tl.store(
                OUT_ptr + pid_b * stride_ob + c * stride_oc + s_off * stride_on,
                state, mask=s_mask
            )


    def parallel_prefix_scan(log_decay, contributions):
        """
        Parallel prefix scan for inter-chunk state propagation.

        Args:
            log_decay: (B, H, n_chunks) — log of decay per chunk
            contributions: (B, H, n_chunks, NP) — chunk boundary states

        Returns:
            states: (B, H, n_chunks, NP) — cumulative states after each chunk
        """
        B, H, n_chunks, NP = contributions.shape

        log_decay_flat = log_decay.reshape(B * H, n_chunks).contiguous()
        contrib_flat = contributions.reshape(B * H, n_chunks, NP).contiguous()
        out_flat = torch.empty_like(contrib_flat)

        BLOCK_NP = min(triton.next_power_of_2(NP), 128)
        grid = (B * H, triton.cdiv(NP, BLOCK_NP))

        _prefix_scan_kernel[grid](
            log_decay_flat, log_decay_flat.stride(0), log_decay_flat.stride(1),
            contrib_flat, contrib_flat.stride(0), contrib_flat.stride(1), contrib_flat.stride(2),
            out_flat, out_flat.stride(0), out_flat.stride(1), out_flat.stride(2),
            N_CHUNKS=n_chunks, NP=NP, BLOCK_NP=BLOCK_NP,
        )

        return out_flat.reshape(B, H, n_chunks, NP)


    # ---------- Kernel 3: Fused CG Lift ----------
    # Fuses: extract real/imag -> power spectrum -> cross-freq -> harmonics -> linear proj
    # into a single kernel per (batch, time, head) element.

    @triton.jit
    def _fused_cg_lift_kernel(
        # Input k_rot: (B*T*H, N) interleaved
        K_ptr, stride_kb, stride_kn,
        # Cross-frequency index pairs (n_cross,) each
        CROSS_I_ptr, CROSS_J_ptr, CROSS_SCALE_ptr,
        # Harmonic indices (n_harm,)
        HARM_IDX_ptr,
        # Projection weight: (rank, D_feat)
        PROJ_ptr, stride_pr, stride_pf,
        # Output: (B*T*H, rank)
        OUT_ptr, stride_ob, stride_or,
        # Dims
        N_HALF: tl.constexpr,
        N_CROSS: tl.constexpr,
        N_HARM: tl.constexpr,
        D_FEAT: tl.constexpr,
        RANK: tl.constexpr,
        BLOCK_R: tl.constexpr,
    ):
        """Fused CG lift: extract invariant features + project to rank."""
        pid_b = tl.program_id(0)   # batch*time*head
        pid_r = tl.program_id(1)   # rank block

        r_off = pid_r * BLOCK_R + tl.arange(0, BLOCK_R)
        r_mask = r_off < RANK

        # We'll compute the dot product proj[r, :] · features[:] for each r
        # Features are computed on-the-fly from k_rot

        # Load all of k_rot for this element (N values)
        # Split into real/imag
        acc = tl.zeros((BLOCK_R,), dtype=tl.float32)

        # --- Tier 1: Power spectrum (N_HALF features at indices 0..N_HALF-1) ---
        for m in range(N_HALF):
            kr = tl.load(K_ptr + pid_b * stride_kb + (2 * m) * stride_kn).to(tl.float32)
            ki = tl.load(K_ptr + pid_b * stride_kb + (2 * m + 1) * stride_kn).to(tl.float32)
            feat = kr * kr + ki * ki  # power spectrum

            # proj[r, m] * feat
            w = tl.load(PROJ_ptr + r_off * stride_pr + m * stride_pf, mask=r_mask, other=0.0)
            acc += w * feat

        # --- Tier 2: Cross-frequency (N_CROSS features at indices N_HALF..N_HALF+N_CROSS-1) ---
        for c in range(N_CROSS):
            idx_i = tl.load(CROSS_I_ptr + c)
            idx_j = tl.load(CROSS_J_ptr + c)
            scale = tl.load(CROSS_SCALE_ptr + c)

            kr_i = tl.load(K_ptr + pid_b * stride_kb + (2 * idx_i) * stride_kn).to(tl.float32)
            ki_i = tl.load(K_ptr + pid_b * stride_kb + (2 * idx_i + 1) * stride_kn).to(tl.float32)
            kr_j = tl.load(K_ptr + pid_b * stride_kb + (2 * idx_j) * stride_kn).to(tl.float32)
            ki_j = tl.load(K_ptr + pid_b * stride_kb + (2 * idx_j + 1) * stride_kn).to(tl.float32)

            feat = (kr_i * kr_j + ki_i * ki_j) * scale
            feat_idx = N_HALF + c
            w = tl.load(PROJ_ptr + r_off * stride_pr + feat_idx * stride_pf, mask=r_mask, other=0.0)
            acc += w * feat

        # --- Tier 3: Harmonics (2*N_HARM features) ---
        for h in range(N_HARM):
            idx = tl.load(HARM_IDX_ptr + h)
            kr = tl.load(K_ptr + pid_b * stride_kb + (2 * idx) * stride_kn).to(tl.float32)
            ki = tl.load(K_ptr + pid_b * stride_kb + (2 * idx + 1) * stride_kn).to(tl.float32)

            feat_re = kr * kr - ki * ki
            feat_im = 2.0 * kr * ki

            feat_idx_re = N_HALF + N_CROSS + h
            feat_idx_im = N_HALF + N_CROSS + N_HARM + h

            w_re = tl.load(PROJ_ptr + r_off * stride_pr + feat_idx_re * stride_pf, mask=r_mask, other=0.0)
            w_im = tl.load(PROJ_ptr + r_off * stride_pr + feat_idx_im * stride_pf, mask=r_mask, other=0.0)
            acc += w_re * feat_re + w_im * feat_im

        # Store result
        tl.store(OUT_ptr + pid_b * stride_ob + r_off * stride_or, acc.to(tl.float16), mask=r_mask)

else:
    # Fallback: no Triton available
    fused_rope = None
    parallel_prefix_scan = None

"""## 3. PyTorch Fallback Ops (used when Triton unavailable)"""

def rope_rotate_pt(u, theta):
    """PyTorch fallback for RoPE rotation."""
    out = torch.empty_like(u)
    ue, uo = u[..., 0::2], u[..., 1::2]
    cos_t, sin_t = torch.cos(theta), torch.sin(theta)
    out[..., 0::2] = ue * cos_t - uo * sin_t
    out[..., 1::2] = ue * sin_t + uo * cos_t
    return out


def build_cumulative_angles_pt(delta, omega):
    """PyTorch fallback: cumsum angles."""
    inc = delta.unsqueeze(-1) * omega.unsqueeze(0).unsqueeze(0)
    return torch.cumsum(inc, dim=1)


def _robust_cholesky(G, max_retries=4):
    G_sym = 0.5 * (G + G.transpose(-1, -2))
    for attempt in range(max_retries):
        try:
            return torch.linalg.cholesky(G_sym)
        except torch.linalg.LinAlgError:
            jitter = 1e-4 * (10 ** attempt)
            eye = torch.eye(G_sym.shape[-1], device=G_sym.device, dtype=G_sym.dtype)
            G_sym = G_sym + jitter * eye
    eigvals, eigvecs = torch.linalg.eigh(G_sym)
    eigvals = eigvals.clamp(min=1e-6)
    return torch.linalg.cholesky(
        eigvecs @ torch.diag_embed(eigvals) @ eigvecs.transpose(-1, -2))


def _spectral_normalize_power_iter(A, n_iters=6):
    r = A.shape[-1]
    v = torch.ones(*A.shape[:-1], 1, device=A.device, dtype=A.dtype) / math.sqrt(r)
    with torch.no_grad():
        for _ in range(n_iters):
            Av = A @ v
            u = Av / Av.norm(dim=-2, keepdim=True).clamp(min=1e-8)
            Atu = A.transpose(-1, -2) @ u
            v = Atu / Atu.norm(dim=-2, keepdim=True).clamp(min=1e-8)
        sigma = (A @ v).norm(dim=-2, keepdim=False).squeeze(-1)
    scale = torch.clamp(sigma, min=1.0).unsqueeze(-1).unsqueeze(-1)
    return A / scale, sigma

"""## 4. Model Configuration"""

@dataclass
class ModelConfig:
    # Architecture — scaled for ~8M params
    d_model: int = 256
    n_heads: int = 8
    d_state: int = 32
    n_layers: int = 6
    vocab_size: int = 8192          # BPE tokenizer
    max_seq_len: int = 2048

    # Mamba recurrence
    delta_min: float = 1e-3
    delta_max: float = 1.0
    alpha_max: float = 0.999
    chunk_size: int = 64

    # SKA config
    ska_layers: List[int] = field(default_factory=lambda: [4, 5])
    ska_rank: int = 32
    ska_ridge: float = 1e-3
    ska_scale: float = 1.5
    power_K: int = 2
    ska_spectral_norm: bool = True
    ska_seq_max_norm: bool = True
    cg_mode: str = 'principled'     # 'principled', 'legacy', 'independent'

    # Training
    lr: float = 3e-4
    batch_size: int = 16
    grad_accum: int = 2             # effective batch = 32
    n_steps: int = 10000
    warmup_steps: int = 500
    eval_every: int = 500
    weight_decay: float = 0.01

    # Special token IDs (set after tokenizer is built)
    pad_id: int = 0
    bos_id: int = 1
    eos_id: int = 2
    func_schema_id: int = 3
    user_id: int = 4
    call_id: int = 5
    result_id: int = 6
    assistant_id: int = 7

    # Use Triton kernels
    use_triton: bool = True

    @property
    def d_head(self):
        return self.d_model // self.n_heads

    @property
    def N_half(self):
        return self.d_state // 2

"""## 5. Principled CG Lift"""

class PrincipledCGLift(nn.Module):
    """Cross-frequency slow invariants from RoPE group theory.
    v8 contribution — Tier 1/2/3 features + learned projection.
    Supports optional Triton-fused forward pass."""

    def __init__(self, N, rank, n_heads, max_cross=48, include_harmonics=True):
        super().__init__()
        self.N_half = N // 2
        self.rank = rank

        base_freq = 1.0 / (10000 ** (torch.arange(0, self.N_half).float() / self.N_half))

        # Slow cross-frequency pairs
        freq_diffs = []
        for i in range(self.N_half):
            for j in range(i + 1, self.N_half):
                diff = abs(base_freq[i].item() - base_freq[j].item())
                freq_diffs.append((diff, i, j))
        freq_diffs.sort(key=lambda x: x[0])
        n_cross = min(len(freq_diffs), max_cross)
        chosen = freq_diffs[:n_cross]

        self.register_buffer('cross_i',
            torch.tensor([p[1] for p in chosen]) if n_cross > 0 else torch.zeros(0, dtype=torch.long))
        self.register_buffer('cross_j',
            torch.tensor([p[2] for p in chosen]) if n_cross > 0 else torch.zeros(0, dtype=torch.long))

        # Low-frequency harmonics
        self.include_harmonics = include_harmonics
        if include_harmonics:
            median_freq = base_freq.median().item()
            self.register_buffer('harmonic_idx', torch.where(base_freq < median_freq)[0])
        else:
            self.register_buffer('harmonic_idx', torch.zeros(0, dtype=torch.long))

        n_harmonic = 2 * len(self.harmonic_idx)
        self.D_feat = self.N_half + n_cross + n_harmonic

        self.proj = nn.Linear(self.D_feat, rank, bias=False)
        nn.init.orthogonal_(self.proj.weight)

        if n_cross > 0:
            self.cross_scale = nn.Parameter(torch.ones(n_cross) * 0.5)
        else:
            self.cross_scale = None

    def forward(self, k_rot, use_triton_kernel=False):
        """k_rot: (B, T, H, N) interleaved. Returns (B, T, H, rank)."""
        # Triton fused path
        if use_triton_kernel and HAS_TRITON and k_rot.is_cuda:
            return self._forward_triton(k_rot)
        return self._forward_pytorch(k_rot)

    def _forward_pytorch(self, k_rot):
        kr = k_rot[..., 0::2]
        ki = k_rot[..., 1::2]
        feats = [kr ** 2 + ki ** 2]

        if len(self.cross_i) > 0:
            kr_i, kr_j = kr[..., self.cross_i], kr[..., self.cross_j]
            ki_i, ki_j = ki[..., self.cross_i], ki[..., self.cross_j]
            feats.append((kr_i * kr_j + ki_i * ki_j) * self.cross_scale)

        if self.include_harmonics and len(self.harmonic_idx) > 0:
            kr_h, ki_h = kr[..., self.harmonic_idx], ki[..., self.harmonic_idx]
            feats.append(kr_h ** 2 - ki_h ** 2)
            feats.append(2 * kr_h * ki_h)

        return self.proj(torch.cat(feats, dim=-1))

    def _forward_triton(self, k_rot):
        """Triton-fused CG lift."""
        B, T, H, N = k_rot.shape
        k_flat = k_rot.reshape(B * T * H, N).contiguous()
        out_flat = torch.empty(B * T * H, self.rank, device=k_rot.device, dtype=torch.float16)

        n_cross = len(self.cross_i)
        n_harm = len(self.harmonic_idx)
        BLOCK_R = min(triton.next_power_of_2(self.rank), 64)

        grid = (B * T * H, triton.cdiv(self.rank, BLOCK_R))

        cross_scale = self.cross_scale if self.cross_scale is not None else torch.zeros(1, device=k_rot.device)

        _fused_cg_lift_kernel[grid](
            k_flat, k_flat.stride(0), k_flat.stride(1),
            self.cross_i, self.cross_j, cross_scale,
            self.harmonic_idx,
            self.proj.weight, self.proj.weight.stride(0), self.proj.weight.stride(1),
            out_flat, out_flat.stride(0), out_flat.stride(1),
            N_HALF=self.N_half, N_CROSS=n_cross, N_HARM=n_harm,
            D_FEAT=self.D_feat, RANK=self.rank, BLOCK_R=BLOCK_R,
        )
        return out_flat.reshape(B, T, H, self.rank).to(k_rot.dtype)


class LegacyCGLift(nn.Module):
    """v7 CG lift — power spectrum + self-harmonics only."""
    def __init__(self, N, rank, use_harmonic=False):
        super().__init__()
        self.N_half = N // 2
        self.use_harmonic = use_harmonic
        D_feat = self.N_half if not use_harmonic else 3 * self.N_half
        self.proj = nn.Linear(D_feat, rank, bias=False)
        nn.init.orthogonal_(self.proj.weight)

    def forward(self, k_rot, use_triton_kernel=False):
        kr, ki = k_rot[..., 0::2], k_rot[..., 1::2]
        psi = kr ** 2 + ki ** 2
        if self.use_harmonic:
            psi = torch.cat([psi, kr ** 2 - ki ** 2, 2 * kr * ki], dim=-1)
        return self.proj(psi)

"""## 6. Recurrence — Chunked SSD with Triton Prefix Scan"""

def _segsum_lower_tri(log_alpha_chunk):
    C = log_alpha_chunk.shape[-1]
    cumsum = torch.cumsum(log_alpha_chunk, dim=-1)
    L_log = cumsum.unsqueeze(-1) - cumsum.unsqueeze(-2)
    mask = torch.tril(torch.ones(C, C, device=log_alpha_chunk.device, dtype=torch.bool))
    return torch.exp(L_log.masked_fill(~mask, -float('inf')))


def run_recurrence(k_real, k_imag, v, q_real, q_imag,
                   alpha, beta, gamma, chunk_size=64, use_triton=True):
    """Chunked SSD recurrence with optional Triton-accelerated prefix scan."""
    B, T, H, N_half = k_real.shape
    P = v.shape[-1]
    dev = v.device
    C = chunk_size

    # Precompute inputs
    U_real = k_real.unsqueeze(-1) * v.unsqueeze(-2)
    U_imag = k_imag.unsqueeze(-1) * v.unsqueeze(-2)
    U_real_prev = F.pad(U_real[:, :-1], (0, 0, 0, 0, 0, 0, 1, 0))
    U_imag_prev = F.pad(U_imag[:, :-1], (0, 0, 0, 0, 0, 0, 1, 0))
    beta_e = beta.unsqueeze(-1).unsqueeze(-1)
    gamma_e = gamma.unsqueeze(-1).unsqueeze(-1)
    b_real = (beta_e * U_real_prev + gamma_e * U_real).float()
    b_imag = (beta_e * U_imag_prev + gamma_e * U_imag).float()
    alpha_f32 = alpha.float()
    q_real_f32, q_imag_f32 = q_real.float(), q_imag.float()

    # Pad to chunk boundary
    T_orig = T
    if T % C != 0:
        pad_len = C - (T % C)
        b_real = F.pad(b_real, (0, 0, 0, 0, 0, 0, 0, pad_len))
        b_imag = F.pad(b_imag, (0, 0, 0, 0, 0, 0, 0, pad_len))
        alpha_f32 = F.pad(alpha_f32, (0, 0, 0, pad_len), value=1e-8)
        q_real_f32 = F.pad(q_real_f32, (0, 0, 0, 0, 0, pad_len))
        q_imag_f32 = F.pad(q_imag_f32, (0, 0, 0, 0, 0, pad_len))
        T = b_real.shape[1]

    n_chunks = T // C
    NP = N_half * P

    # Reshape into chunks
    b_re_c = b_real.reshape(B, n_chunks, C, H, N_half, P)
    b_im_c = b_imag.reshape(B, n_chunks, C, H, N_half, P)
    alpha_c = alpha_f32.reshape(B, n_chunks, C, H)
    log_alpha = torch.log(alpha_c.clamp(min=1e-8)).permute(0, 3, 1, 2)  # (B, H, n_chunks, C)

    b_re_bh = b_re_c.permute(0, 3, 1, 2, 4, 5).reshape(B, H, n_chunks, C, NP)
    b_im_bh = b_im_c.permute(0, 3, 1, 2, 4, 5).reshape(B, H, n_chunks, C, NP)

    # Intra-chunk: lower-triangular matmul
    L = _segsum_lower_tri(log_alpha)
    H_re_intra = torch.matmul(L, b_re_bh)
    H_im_intra = torch.matmul(L, b_im_bh)

    # Chunk boundary states
    chunk_states_re = H_re_intra[:, :, :, -1, :]  # (B, H, n_chunks, NP)
    chunk_states_im = H_im_intra[:, :, :, -1, :]
    chunk_decay_log = log_alpha.sum(dim=-1)  # (B, H, n_chunks)

    # Inter-chunk: prefix scan
    use_triton_scan = (use_triton and HAS_TRITON and dev.type == 'cuda'
                       and n_chunks > 1)

    if use_triton_scan:
        # Triton parallel prefix scan
        true_states_re = parallel_prefix_scan(chunk_decay_log, chunk_states_re)
        true_states_im = parallel_prefix_scan(chunk_decay_log, chunk_states_im)
    else:
        # PyTorch serial fallback
        true_states_re = torch.zeros(B, H, n_chunks, NP, device=dev, dtype=torch.float32)
        true_states_im = torch.zeros(B, H, n_chunks, NP, device=dev, dtype=torch.float32)
        prev_re = torch.zeros(B, H, NP, device=dev, dtype=torch.float32)
        prev_im = torch.zeros(B, H, NP, device=dev, dtype=torch.float32)
        for c in range(n_chunks):
            decay = torch.exp(chunk_decay_log[:, :, c]).unsqueeze(-1)
            prev_re = decay * prev_re + chunk_states_re[:, :, c]
            prev_im = decay * prev_im + chunk_states_im[:, :, c]
            true_states_re[:, :, c] = prev_re
            true_states_im[:, :, c] = prev_im

    # Combine intra + inter
    cumsum_within = torch.cumsum(log_alpha, dim=-1)
    decay_from_start = torch.exp(cumsum_within)
    init_states_re = F.pad(true_states_re[:, :, :-1], (0, 0, 1, 0))
    init_states_im = F.pad(true_states_im[:, :, :-1], (0, 0, 1, 0))
    H_re_off = decay_from_start.unsqueeze(-1) * init_states_re.unsqueeze(-2)
    H_im_off = decay_from_start.unsqueeze(-1) * init_states_im.unsqueeze(-2)

    H_re_full = (H_re_intra + H_re_off).reshape(B, H, n_chunks, C, N_half, P)
    H_im_full = (H_im_intra + H_im_off).reshape(B, H, n_chunks, C, N_half, P)
    H_re_full = H_re_full.permute(0, 2, 3, 1, 4, 5).reshape(B, T, H, N_half, P)
    H_im_full = H_im_full.permute(0, 2, 3, 1, 4, 5).reshape(B, T, H, N_half, P)

    y = (torch.einsum('bthn,bthnp->bthp', q_real_f32, H_re_full) +
         torch.einsum('bthn,bthnp->bthp', q_imag_f32, H_im_full))
    return y[:, :T_orig].to(v.dtype)

"""## 7. Mamba-3 Block"""

class Mamba3Block(nn.Module):
    def __init__(self, cfg: ModelConfig):
        super().__init__()
        self.cfg = cfg
        H, N, P, d = cfg.n_heads, cfg.d_state, cfg.d_head, cfg.d_model
        proj_size = H * N + H * N + H * P + H + H + H
        self.in_proj = nn.Linear(d, proj_size, bias=False)
        self.out_proj = nn.Linear(d, d, bias=False)
        self.norm = nn.LayerNorm(d)
        self.delta_bias = nn.Parameter(torch.zeros(H))
        self.a_bias = nn.Parameter(torch.log(torch.linspace(0.5, 2.0, H)))

        N_half = N // 2
        base_freq = 1.0 / (10000 ** (torch.arange(0, N_half).float() / N_half))
        self.register_buffer('omega_base', base_freq.unsqueeze(0).expand(H, -1))
        self.omega_scale = nn.Parameter(torch.ones(H, 1))
        self.conv1d = nn.Conv1d(d, d, kernel_size=4, padding=3, groups=d, bias=True)

    @property
    def omega(self):
        return self.omega_scale * self.omega_base

    def forward(self, x, return_aux=False):
        B, T, d = x.shape
        C = self.cfg
        H, N, P = C.n_heads, C.d_state, C.d_head
        residual = x
        x = self.norm(x)

        proj = self.in_proj(x)
        idx = 0
        b_raw = proj[..., idx:idx + H * N].reshape(B, T, H, N); idx += H * N
        c_raw = proj[..., idx:idx + H * N].reshape(B, T, H, N); idx += H * N
        v_flat = proj[..., idx:idx + H * P]; idx += H * P
        delta_raw = proj[..., idx:idx + H].reshape(B, T, H); idx += H
        a_raw = proj[..., idx:idx + H].reshape(B, T, H); idx += H
        lam_raw = proj[..., idx:idx + H].reshape(B, T, H); idx += H

        v_conv = self.conv1d(v_flat.transpose(1, 2))[..., :T].transpose(1, 2)
        v = F.silu(v_conv).reshape(B, T, H, P)

        delta = torch.clamp(F.softplus(delta_raw + self.delta_bias), C.delta_min, C.delta_max)
        a = F.softplus(a_raw + self.a_bias)
        alpha = torch.clamp(torch.exp(-a * delta), max=C.alpha_max)
        lam = torch.sigmoid(lam_raw)
        beta = (1.0 - lam) * delta * alpha
        gamma = lam * delta

        # RoPE rotation — use Triton fused kernel if available
        use_triton = C.use_triton and HAS_TRITON and x.is_cuda
        if use_triton and fused_rope is not None:
            k_rot = fused_rope(b_raw, delta, self.omega)
            q_rot = fused_rope(c_raw, delta, self.omega)
        else:
            theta = build_cumulative_angles_pt(delta, self.omega)
            k_rot = rope_rotate_pt(b_raw, theta)
            q_rot = rope_rotate_pt(c_raw, theta)

        y = run_recurrence(
            k_rot[..., 0::2], k_rot[..., 1::2], v,
            q_rot[..., 0::2], q_rot[..., 1::2],
            alpha, beta, gamma,
            chunk_size=C.chunk_size, use_triton=use_triton)

        y = self.out_proj(y.reshape(B, T, d))
        aux = None
        if return_aux:
            aux = {'k_rot': k_rot, 'q_rot': q_rot, 'v': v, 'alpha': alpha}
        return y + residual, aux

"""## 8. SKA Module"""

class SKAModule(nn.Module):
    """Spectral Koopman Attention — v8 with principled CG lift."""

    def __init__(self, N, P, rank=32, ridge_eps=1e-3, scale=1.5,
                 power_K=2, cg_mode='principled',
                 use_spectral_norm=True, use_seq_max_norm=True,
                 d_model=None, n_heads=None):
        super().__init__()
        self.rank = rank
        self.ridge_eps = ridge_eps
        self.power_K = power_K
        self.use_spectral_norm = use_spectral_norm
        self.use_seq_max_norm = use_seq_max_norm
        self.cg_mode = cg_mode

        if cg_mode == 'independent':
            assert d_model and n_heads
            H = n_heads
            self.ska_key_proj = nn.Linear(d_model, H * rank, bias=False)
            self.ska_query_proj = nn.Linear(d_model, H * rank, bias=False)
            self.ska_value_proj = nn.Linear(d_model, H * P, bias=False)
            nn.init.orthogonal_(self.ska_key_proj.weight)
            nn.init.orthogonal_(self.ska_query_proj.weight)
            self.cg_lift = None
        elif cg_mode == 'principled':
            self.cg_lift = PrincipledCGLift(N, rank, n_heads or 8)
        elif cg_mode == 'legacy':
            self.cg_lift = LegacyCGLift(N, rank, use_harmonic=True)
        else:
            raise ValueError(f"Unknown cg_mode: {cg_mode}")

        self.eta = nn.Parameter(torch.tensor(scale))
        self.ssn_gamma = nn.Parameter(torch.tensor(1.0))

    def forward(self, k_rot_or_h, q_rot_or_none, v_or_none, prefix_mask,
                use_triton_kernel=False):
        if self.cg_mode == 'independent':
            h = k_rot_or_h
            B, T, _ = h.shape
            H = self.ska_key_proj.out_features // self.rank
            P = self.ska_value_proj.out_features // H
            r = self.rank
            z = self.ska_key_proj(h).reshape(B, T, H, r)
            zq = self.ska_query_proj(h).reshape(B, T, H, r)
            v_ska = self.ska_value_proj(h).reshape(B, T, H, P)
        else:
            B, T, H, N = k_rot_or_h.shape
            P = v_or_none.shape[-1]
            r = self.rank
            z = self.cg_lift(k_rot_or_h, use_triton_kernel=use_triton_kernel)
            zq = self.cg_lift(q_rot_or_none, use_triton_kernel=use_triton_kernel)
            v_ska = v_or_none

        ska_mask = prefix_mask
        ctx = (torch.amp.autocast('cuda', enabled=False)
               if torch.cuda.is_available() else nullcontext())

        with ctx:
            z_f, v_f, zq_f = z.float(), v_ska.float(), zq.float()
            m = ska_mask.float().unsqueeze(-1).unsqueeze(-1)

            if self.use_seq_max_norm:
                z_norms = z_f.norm(dim=-1, keepdim=True)
                max_norm = z_norms.max(dim=1, keepdim=True)[0]
                z_f = z_f / (max_norm + 1e-6)
                zq_f = zq_f / (max_norm + 1e-6)

            z_m = z_f * m
            G = torch.einsum('bthr,bths->bhrs', z_m, z_m)
            m_lag = (ska_mask[:, :-1] * ska_mask[:, 1:]).float().unsqueeze(-1).unsqueeze(-1)
            M_cov = torch.einsum('bthr,bths->bhrs',
                                 z_f[:, 1:] * m_lag, z_f[:, :-1] * m_lag)
            C_v = torch.einsum('bthp,bthr->bhpr', v_f * m, z_f * m)

            G_tilde = G + self.ridge_eps * torch.eye(r, device=G.device, dtype=torch.float32)
            L = _robust_cholesky(G_tilde)

            Y = torch.linalg.solve_triangular(L, M_cov, upper=False)
            Aw_T = torch.linalg.solve_triangular(L, Y.transpose(-1, -2), upper=False)
            A_w = Aw_T.transpose(-1, -2)

            if self.use_spectral_norm:
                A_w, sigma = _spectral_normalize_power_iter(A_w)
                A_w = A_w * torch.clamp(self.ssn_gamma, min=1.0, max=1.5)

            B_v = torch.cholesky_solve(C_v.transpose(-1, -2), L).transpose(-1, -2)

            zq_perm = zq_f.permute(0, 2, 3, 1)
            w_q = torch.linalg.solve_triangular(L, zq_perm, upper=False)
            # Power filter
            w_f = w_q
            for _ in range(self.power_K - 1):
                w_f = A_w @ w_f
            w_f = A_w @ w_f
            z_f_out = L @ w_f
            y_hat = (B_v @ z_f_out).permute(0, 3, 1, 2)

        return self.eta * y_hat.to(z.dtype)

"""## 9. Full Model — Mamba-3 + SKA LM (~8M params)"""

class SwiGLUMLP(nn.Module):
    def __init__(self, d, expand=8 / 3):
        super().__init__()
        d_ff = ((int(d * expand) + 63) // 64) * 64
        self.norm = nn.LayerNorm(d)
        self.w1 = nn.Linear(d, d_ff, bias=False)
        self.w2 = nn.Linear(d, d_ff, bias=False)
        self.w3 = nn.Linear(d_ff, d, bias=False)

    def forward(self, x):
        h = self.norm(x)
        return x + self.w3(F.silu(self.w1(h)) * self.w2(h))


class Mamba3LM(nn.Module):
    """Baseline Mamba-3 language model."""
    def __init__(self, cfg: ModelConfig):
        super().__init__()
        self.cfg = cfg
        self.embed = nn.Embedding(cfg.vocab_size, cfg.d_model)
        self.blocks = nn.ModuleList([Mamba3Block(cfg) for _ in range(cfg.n_layers)])
        self.mlps = nn.ModuleList([SwiGLUMLP(cfg.d_model) for _ in range(cfg.n_layers)])
        self.norm_f = nn.LayerNorm(cfg.d_model)
        self.lm_head = nn.Linear(cfg.d_model, cfg.vocab_size, bias=False)
        # Weight tying
        self.lm_head.weight = self.embed.weight
        self.name = "Mamba-3"

    def forward(self, x, prefix_mask=None, loss_mask=None):
        h = self.embed(x)
        for blk, mlp in zip(self.blocks, self.mlps):
            h, _ = blk(h)
            h = mlp(h)
        return self.lm_head(self.norm_f(h)), {}


class Mamba3SKALM(nn.Module):
    """Mamba-3 + SKA language model."""
    def __init__(self, cfg: ModelConfig):
        super().__init__()
        self.cfg = cfg
        self.embed = nn.Embedding(cfg.vocab_size, cfg.d_model)
        self.blocks = nn.ModuleList([Mamba3Block(cfg) for _ in range(cfg.n_layers)])
        self.mlps = nn.ModuleList([SwiGLUMLP(cfg.d_model) for _ in range(cfg.n_layers)])
        self.ska_modules = nn.ModuleDict()
        self.ska_norms = nn.ModuleDict()

        for i in range(cfg.n_layers):
            if i in cfg.ska_layers:
                self.ska_modules[str(i)] = SKAModule(
                    N=cfg.d_state, P=cfg.d_head, rank=cfg.ska_rank,
                    ridge_eps=cfg.ska_ridge, scale=cfg.ska_scale,
                    power_K=cfg.power_K, cg_mode=cfg.cg_mode,
                    use_spectral_norm=cfg.ska_spectral_norm,
                    use_seq_max_norm=cfg.ska_seq_max_norm,
                    d_model=cfg.d_model, n_heads=cfg.n_heads)
                if cfg.cg_mode == 'independent':
                    self.ska_norms[str(i)] = nn.LayerNorm(cfg.d_model)

        self.norm_f = nn.LayerNorm(cfg.d_model)
        self.lm_head = nn.Linear(cfg.d_model, cfg.vocab_size, bias=False)
        self.embed.weight = self.lm_head.weight  # tie
        self.ska_proj = nn.Linear(cfg.d_model, cfg.d_model, bias=False)
        self.name = f"Mamba-3+SKA({cfg.cg_mode})"

    def forward(self, x, prefix_mask=None, loss_mask=None):
        h = self.embed(x)
        use_triton = self.cfg.use_triton and HAS_TRITON and x.is_cuda

        for i, (blk, mlp) in enumerate(zip(self.blocks, self.mlps)):
            has_ska = str(i) in self.ska_modules
            h, aux = blk(h, return_aux=(has_ska and self.cfg.cg_mode != 'independent'))

            if has_ska and prefix_mask is not None:
                ska_mod = self.ska_modules[str(i)]
                if self.cfg.cg_mode == 'independent':
                    h_normed = self.ska_norms[str(i)](h)
                    ska_out = ska_mod(h_normed, None, None, prefix_mask,
                                      use_triton_kernel=use_triton)
                else:
                    if aux is not None:
                        ska_out = ska_mod(aux['k_rot'], aux['q_rot'], aux['v'],
                                          prefix_mask, use_triton_kernel=use_triton)
                    else:
                        ska_out = None

                if ska_out is not None:
                    Bs, Ts, Hs, Ps = ska_out.shape
                    h = h + self.ska_proj(ska_out.reshape(Bs, Ts, self.cfg.d_model))

            h = mlp(h)
        return self.lm_head(self.norm_f(h)), {}

"""## 10. BPE Tokenizer (trained on tool-call data)"""

SPECIAL_TOKENS = [
    "<pad>", "<bos>", "<eos>",
    "<func_schema>", "<user>", "<call>", "<result>", "<assistant>",
    "<func_name>", "</func_name>", "<args>", "</args>",
    "<sep>",
]


def build_tokenizer(texts, vocab_size=8192, special_tokens=None):
    """Train a BPE tokenizer on the given texts using HuggingFace tokenizers."""
    from tokenizers import Tokenizer, models, trainers, pre_tokenizers, processors

    if special_tokens is None:
        special_tokens = SPECIAL_TOKENS

    tokenizer = Tokenizer(models.BPE())
    tokenizer.pre_tokenizer = pre_tokenizers.ByteLevel(add_prefix_space=False)

    trainer = trainers.BpeTrainer(
        vocab_size=vocab_size,
        special_tokens=special_tokens,
        min_frequency=2,
        show_progress=True,
    )

    # Train from iterator
    tokenizer.train_from_iterator(texts, trainer=trainer)
    tokenizer.post_processor = processors.ByteLevel(trim_offsets=False)

    return tokenizer

"""## 11. Data Pipeline — ToolAlpaca from HuggingFace"""

def load_toolalpaca():
    """Load ToolAlpaca dataset from HuggingFace."""
    from datasets import load_dataset

    print("Loading ToolAlpaca dataset...")
    ds = load_dataset("TangQiaoYu/ToolAlpaca", split="train", trust_remote_code=True)
    print(f"  Loaded {len(ds)} examples")
    return ds


def format_tool_call_example(example):
    """
    Format a ToolAlpaca example into our training format.

    Format:
        <func_schema> {function_definitions} <sep>
        <user> {user_query} <sep>
        <call> <func_name> {name} </func_name> <args> {args_json} </args> <sep>
        <result> {result} <sep>
        <assistant> {response} <eos>
    """
    parts = []

    # Function schema
    if 'Functions' in example and example['Functions']:
        funcs = example['Functions']
        if isinstance(funcs, str):
            try:
                funcs = json.loads(funcs)
            except (json.JSONDecodeError, TypeError):
                funcs = funcs
        parts.append(f"<func_schema> {json.dumps(funcs) if isinstance(funcs, (list, dict)) else str(funcs)} <sep>")

    # Conversation turns
    if 'Instances' in example and example['Instances']:
        instances = example['Instances']
        if isinstance(instances, str):
            try:
                instances = json.loads(instances)
            except (json.JSONDecodeError, TypeError):
                instances = [{'input': instances, 'output': ''}]
        if isinstance(instances, dict):
            instances = [instances]

        for inst in instances:
            if isinstance(inst, dict):
                user_input = inst.get('input', inst.get('query', ''))
                if user_input:
                    parts.append(f"<user> {user_input} <sep>")

                # Check for intermediate tool calls
                intermediate = inst.get('intermediate_steps', inst.get('tool_calls', []))
                if intermediate:
                    if isinstance(intermediate, str):
                        try:
                            intermediate = json.loads(intermediate)
                        except (json.JSONDecodeError, TypeError):
                            intermediate = []
                    if isinstance(intermediate, list):
                        for step in intermediate:
                            if isinstance(step, dict):
                                fname = step.get('tool', step.get('function', step.get('name', 'unknown')))
                                fargs = step.get('tool_input', step.get('arguments', step.get('args', {})))
                                fresult = step.get('observation', step.get('result', ''))
                                args_str = json.dumps(fargs) if isinstance(fargs, dict) else str(fargs)
                                parts.append(f"<call> <func_name> {fname} </func_name> <args> {args_str} </args> <sep>")
                                if fresult:
                                    parts.append(f"<result> {str(fresult)[:200]} <sep>")
                            elif isinstance(step, (list, tuple)) and len(step) >= 2:
                                parts.append(f"<call> <func_name> {step[0]} </func_name> <args> {json.dumps(step[1]) if isinstance(step[1], dict) else str(step[1])} </args> <sep>")
                                if len(step) > 2 and step[2]:
                                    parts.append(f"<result> {str(step[2])[:200]} <sep>")

                output = inst.get('output', inst.get('response', ''))
                if output:
                    parts.append(f"<assistant> {output} <eos>")

    return "\n".join(parts) if parts else None


class ToolCallDataset(Dataset):
    """Dataset for tool-call pretraining."""

    def __init__(self, tokenizer, examples, max_len=2048):
        self.tokenizer = tokenizer
        self.max_len = max_len
        self.data = []

        # Special token IDs
        self.call_id = tokenizer.token_to_id("<call>")
        self.assistant_id = tokenizer.token_to_id("<assistant>")
        self.sep_id = tokenizer.token_to_id("<sep>")
        self.eos_id = tokenizer.token_to_id("<eos>")
        self.func_schema_id = tokenizer.token_to_id("<func_schema>")
        self.user_id = tokenizer.token_to_id("<user>")
        self.pad_id = tokenizer.token_to_id("<pad>")
        self.bos_id = tokenizer.token_to_id("<bos>")

        skipped = 0
        for ex in tqdm(examples, desc="Tokenizing"):
            formatted = format_tool_call_example(ex)
            if formatted is None or len(formatted.strip()) < 20:
                skipped += 1
                continue

            encoded = tokenizer.encode(formatted)
            ids = encoded.ids

            if len(ids) < 10:
                skipped += 1
                continue

            # Truncate
            ids = [self.bos_id] + ids[:max_len - 2] + [self.eos_id]
            self.data.append(ids)

        print(f"  Prepared {len(self.data)} examples, skipped {skipped}")

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        ids = self.data[idx]
        T = len(ids) - 1
        x = torch.tensor(ids[:-1], dtype=torch.long)
        y = torch.tensor(ids[1:], dtype=torch.long)

        # Loss mask: only on <call>, <assistant>, and their content tokens
        # (not on <func_schema> or <user> input — those are context)
        loss_mask = torch.zeros(T, dtype=torch.float32)
        prefix_mask = torch.ones(T, dtype=torch.float32)

        in_output = False
        for t in range(T):
            tok = x[t].item()
            if tok == self.call_id or tok == self.assistant_id:
                in_output = True
            elif tok == self.sep_id or tok == self.eos_id:
                if in_output:
                    loss_mask[t] = 1.0  # include the separator
                in_output = False
            elif tok == self.func_schema_id or tok == self.user_id:
                in_output = False

            if in_output:
                loss_mask[t] = 1.0

        return x, y, loss_mask, prefix_mask


def collate_fn(batch):
    """Pad and collate."""
    max_len = max(x.shape[0] for x, *_ in batch)
    B = len(batch)
    x_pad = torch.zeros(B, max_len, dtype=torch.long)
    y_pad = torch.zeros(B, max_len, dtype=torch.long)
    lm_pad = torch.zeros(B, max_len)
    pm_pad = torch.zeros(B, max_len)
    for i, (x, y, lm, pm) in enumerate(batch):
        T = x.shape[0]
        x_pad[i, :T] = x
        y_pad[i, :T] = y
        lm_pad[i, :T] = lm
        pm_pad[i, :T] = pm
    return x_pad, y_pad, lm_pad, pm_pad

"""## 12. Training Loop"""

def get_lr(step, warmup, total, max_lr, min_lr=1e-6):
    if step < warmup:
        return max_lr * step / max(warmup, 1)
    progress = (step - warmup) / max(total - warmup, 1)
    return min_lr + 0.5 * (max_lr - min_lr) * (1.0 + math.cos(math.pi * progress))


def train(model, train_ds, eval_ds, cfg: ModelConfig, device):
    """Main training loop with gradient accumulation and AMP."""
    optimizer = torch.optim.AdamW(
        model.parameters(), lr=cfg.lr, betas=(0.9, 0.95),
        weight_decay=cfg.weight_decay)

    use_amp = HAS_AMP and device.type == 'cuda'
    scaler = amp_scaler() if use_amp else None

    train_loader = DataLoader(
        train_ds, batch_size=cfg.batch_size, shuffle=True,
        collate_fn=collate_fn, drop_last=True, num_workers=2, pin_memory=True)

    eval_loader = DataLoader(
        eval_ds, batch_size=cfg.batch_size, shuffle=False,
        collate_fn=collate_fn, drop_last=True)

    logs = {'step': [], 'train_loss': [], 'eval_loss': [], 'eval_acc': [],
            'lr': [], 'throughput': []}
    step = 0
    best_eval_loss = float('inf')
    data_iter = iter(train_loader)
    t0 = time.time()
    tokens_processed = 0

    model.train()
    pbar = tqdm(total=cfg.n_steps, desc=f"Training {model.name}")

    while step < cfg.n_steps:
        optimizer.zero_grad(set_to_none=True)
        accum_loss = 0.0

        for _ in range(cfg.grad_accum):
            try:
                batch = next(data_iter)
            except StopIteration:
                data_iter = iter(train_loader)
                batch = next(data_iter)

            bx, by, blm, bpm = [t.to(device, non_blocking=True) for t in batch]
            tokens_processed += bx.numel()

            if use_amp:
                with amp_autocast():
                    logits, _ = model(bx, prefix_mask=bpm, loss_mask=blm)
                    loss_all = F.cross_entropy(
                        logits.reshape(-1, logits.size(-1)),
                        by.reshape(-1), reduction='none').reshape_as(by)
                    loss = (loss_all * blm).sum() / blm.sum().clamp(min=1.0)
                    loss = loss / cfg.grad_accum
                scaler.scale(loss).backward()
            else:
                logits, _ = model(bx, prefix_mask=bpm, loss_mask=blm)
                loss_all = F.cross_entropy(
                    logits.reshape(-1, logits.size(-1)),
                    by.reshape(-1), reduction='none').reshape_as(by)
                loss = (loss_all * blm).sum() / blm.sum().clamp(min=1.0)
                loss = loss / cfg.grad_accum
                loss.backward()

            accum_loss += loss.item()

        # LR schedule
        cur_lr = get_lr(step, cfg.warmup_steps, cfg.n_steps, cfg.lr)
        for pg in optimizer.param_groups:
            pg['lr'] = cur_lr

        if use_amp:
            scaler.unscale_(optimizer)
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            scaler.step(optimizer)
            scaler.update()
        else:
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

        # Eval
        if step % cfg.eval_every == 0 or step == cfg.n_steps - 1:
            model.eval()
            eval_loss_sum, eval_count = 0.0, 0
            eval_correct, eval_total = 0, 0
            with torch.no_grad():
                for ebatch in eval_loader:
                    ex, ey, elm, epm = [t.to(device) for t in ebatch]
                    if use_amp:
                        with amp_autocast():
                            elogits, _ = model(ex, prefix_mask=epm)
                    else:
                        elogits, _ = model(ex, prefix_mask=epm)

                    eloss = F.cross_entropy(
                        elogits.reshape(-1, elogits.size(-1)),
                        ey.reshape(-1), reduction='none').reshape_as(ey)
                    eval_loss_sum += (eloss * elm).sum().item()
                    eval_count += elm.sum().item()
                    preds = elogits.argmax(dim=-1)
                    eval_correct += ((preds == ey) * elm).sum().item()
                    eval_total += elm.sum().item()

            model.train()
            eval_loss = eval_loss_sum / max(eval_count, 1)
            eval_acc = eval_correct / max(eval_total, 1)
            elapsed = time.time() - t0
            throughput = tokens_processed / elapsed

            logs['step'].append(step)
            logs['train_loss'].append(accum_loss)
            logs['eval_loss'].append(eval_loss)
            logs['eval_acc'].append(eval_acc)
            logs['lr'].append(cur_lr)
            logs['throughput'].append(throughput)

            if eval_loss < best_eval_loss:
                best_eval_loss = eval_loss

            pbar.set_postfix({
                'loss': f'{accum_loss:.3f}',
                'eval': f'{eval_loss:.3f}',
                'acc': f'{eval_acc:.3f}',
                'tok/s': f'{throughput:.0f}',
                'lr': f'{cur_lr:.1e}'
            })

        step += 1
        pbar.update(1)

    pbar.close()
    return logs, best_eval_loss

"""## 13. Tool-Call Evaluation Metrics"""

def evaluate_tool_calling(model, eval_ds, tokenizer, device, n_samples=200):
    """
    Evaluate tool-calling capability.

    Metrics:
      - Function name accuracy (did it predict the right function?)
      - Argument accuracy (did it get the args right?)
      - Full call accuracy (both name + args correct)
    """
    model.eval()
    call_id = tokenizer.token_to_id("<call>")
    func_name_id = tokenizer.token_to_id("<func_name>")
    end_func_id = tokenizer.token_to_id("</func_name>")
    args_id = tokenizer.token_to_id("<args>")
    end_args_id = tokenizer.token_to_id("</args>")
    sep_id = tokenizer.token_to_id("<sep>")

    results = {
        'func_name_correct': 0,
        'args_correct': 0,
        'full_correct': 0,
        'total': 0,
        'generated_samples': [],
    }

    for idx in range(min(n_samples, len(eval_ds))):
        x, y, lm, pm = eval_ds[idx]
        x = x.unsqueeze(0).to(device)

        # Find the first <call> token position
        call_positions = (x[0] == call_id).nonzero(as_tuple=True)[0]
        if len(call_positions) == 0:
            continue

        # Use context up to just before the <call> token
        call_pos = call_positions[0].item()
        context = x[:, :call_pos + 1]  # include <call> token

        # Generate up to next <sep>
        generated = []
        with torch.no_grad():
            for _ in range(100):
                logits, _ = model(context, prefix_mask=torch.ones(context.shape[1], device=device))
                next_tok = logits[0, -1].argmax().item()
                generated.append(next_tok)
                if next_tok == sep_id or next_tok == tokenizer.token_to_id("<eos>"):
                    break
                context = torch.cat([context, torch.tensor([[next_tok]], device=device)], dim=1)

        # Extract ground truth call from y
        gt_call_tokens = y[call_pos:].tolist()
        gt_sep = gt_call_tokens.index(sep_id) if sep_id in gt_call_tokens else len(gt_call_tokens)
        gt_call = gt_call_tokens[:gt_sep]

        # Compare
        gen_str = tokenizer.decode(generated)
        gt_str = tokenizer.decode(gt_call)

        # Extract function names
        gen_func = _extract_between(gen_str, "<func_name>", "</func_name>")
        gt_func = _extract_between(gt_str, "<func_name>", "</func_name>")

        gen_args = _extract_between(gen_str, "<args>", "</args>")
        gt_args = _extract_between(gt_str, "<args>", "</args>")

        func_match = gen_func.strip() == gt_func.strip() if gen_func and gt_func else False
        args_match = gen_args.strip() == gt_args.strip() if gen_args and gt_args else False

        results['func_name_correct'] += int(func_match)
        results['args_correct'] += int(args_match)
        results['full_correct'] += int(func_match and args_match)
        results['total'] += 1

        if len(results['generated_samples']) < 5:
            results['generated_samples'].append({
                'gt': gt_str, 'gen': gen_str,
                'func_match': func_match, 'args_match': args_match
            })

    total = max(results['total'], 1)
    results['func_name_acc'] = results['func_name_correct'] / total
    results['args_acc'] = results['args_correct'] / total
    results['full_acc'] = results['full_correct'] / total

    return results


def _extract_between(text, start_tag, end_tag):
    """Extract text between two tags."""
    s = text.find(start_tag)
    if s == -1:
        return ""
    s += len(start_tag)
    e = text.find(end_tag, s)
    if e == -1:
        return text[s:]
    return text[s:e]

"""## 14. BFCL Published Results for Comparison"""

# Published BFCL v3 overall scores (approximate, from leaderboard as of 2025)
# These are for MUCH larger models — the comparison shows efficiency, not parity.
BFCL_PUBLISHED = {
    'GPT-4o (2024-11-20)':      {'overall': 0.742, 'params': '~1.8T (est)'},
    'Claude 3.5 Sonnet':        {'overall': 0.689, 'params': '~175B (est)'},
    'Kimi k1.5':                {'overall': 0.652, 'params': 'unknown'},
    'Qwen2.5-72B-Instruct':     {'overall': 0.598, 'params': '72B'},
    'Qwen2.5-7B-Instruct':      {'overall': 0.482, 'params': '7B'},
    'Llama-3.1-8B-Instruct':    {'overall': 0.385, 'params': '8B'},
    'Llama-3.1-70B-Instruct':   {'overall': 0.545, 'params': '70B'},
    'Mistral-7B-Instruct-v0.3': {'overall': 0.341, 'params': '7B'},
}


def print_comparison(our_results, model_name, n_params):
    """Print comparison table against published BFCL results."""
    print(f"\n{'=' * 70}")
    print("COMPARISON: SKA v9 vs Published BFCL Results")
    print(f"{'=' * 70}")
    print(f"\nNote: BFCL scores are from the official leaderboard (full benchmark).")
    print(f"Our scores are on ToolAlpaca eval split (different distribution).")
    print(f"This comparison shows architectural efficiency, not direct equivalence.\n")

    print(f"  {'Model':<35s} {'Params':>10s} {'Tool-Call Acc':>14s}")
    print(f"  {'─' * 62}")

    # Our model
    our_acc = our_results.get('full_acc', 0)
    print(f"  {model_name + ' (ours)':<35s} {f'{n_params/1e6:.1f}M':>10s} {our_acc:>13.1%}")
    print(f"  {'─' * 62}")

    # Published
    for name, info in sorted(BFCL_PUBLISHED.items(), key=lambda x: -x[1]['overall']):
        print(f"  {name:<35s} {info['params']:>10s} {info['overall']:>13.1%}")

    # Efficiency metric
    print(f"\n  Efficiency analysis:")
    for name, info in BFCL_PUBLISHED.items():
        if 'B' in info['params'] and info['params'] != 'unknown':
            try:
                other_params = float(info['params'].replace('B', '').replace('~', '').replace('(est)', '').strip()) * 1e9
                ratio = other_params / n_params
                perf_ratio = our_acc / max(info['overall'], 0.01)
                print(f"    vs {name}: {ratio:.0f}x smaller, {perf_ratio:.1%} of performance")
            except ValueError:
                pass

"""## 15. Main — Run Everything"""

def main():
    print("\n" + "=" * 70)
    print("SKA v9: 8M-Param Tool-Calling LM with Triton Kernels")
    print("=" * 70)

    cfg = ModelConfig()
    device = DEVICE

    # ---- Step 1: Load data ----
    print("\n[1/6] Loading ToolAlpaca dataset...")
    try:
        raw_ds = load_toolalpaca()
    except Exception as e:
        print(f"  Failed to load ToolAlpaca: {e}")
        print("  Falling back to synthetic tool-call data...")
        raw_ds = _generate_synthetic_tool_data(2000)

    # Format examples
    print("\n[2/6] Formatting tool-call examples...")
    formatted = []
    for ex in tqdm(raw_ds, desc="Formatting"):
        if isinstance(ex, dict):
            text = format_tool_call_example(ex)
        else:
            text = str(ex)
        if text and len(text) > 20:
            formatted.append(text)
    print(f"  {len(formatted)} formatted examples")

    # ---- Step 2: Train tokenizer ----
    print("\n[3/6] Training BPE tokenizer (vocab={})...".format(cfg.vocab_size))
    tokenizer = build_tokenizer(formatted, vocab_size=cfg.vocab_size)
    print(f"  Tokenizer ready: {tokenizer.get_vocab_size()} tokens")

    # ---- Step 3: Build datasets ----
    print("\n[4/6] Building train/eval datasets...")
    split = int(0.9 * len(formatted))
    train_examples = [raw_ds[i] for i in range(split)] if hasattr(raw_ds, '__getitem__') else list(raw_ds)[:split]
    eval_examples = [raw_ds[i] for i in range(split, len(raw_ds))] if hasattr(raw_ds, '__getitem__') else list(raw_ds)[split:]

    train_ds = ToolCallDataset(tokenizer, train_examples, max_len=cfg.max_seq_len)
    eval_ds = ToolCallDataset(tokenizer, eval_examples, max_len=cfg.max_seq_len)
    print(f"  Train: {len(train_ds)} | Eval: {len(eval_ds)}")

    # ---- Step 4: Build models ----
    print("\n[5/6] Building models...")

    # Baseline: Mamba-3
    cfg_base = ModelConfig(ska_layers=[], use_triton=cfg.use_triton)
    model_base = Mamba3LM(cfg_base).to(device)
    n_base = sum(p.numel() for p in model_base.parameters())

    # SKA v9: principled CG lift
    cfg_ska = ModelConfig(cg_mode='principled', use_triton=cfg.use_triton)
    model_ska = Mamba3SKALM(cfg_ska).to(device)
    n_ska = sum(p.numel() for p in model_ska.parameters())

    # SKA v9: independent
    cfg_indep = ModelConfig(cg_mode='independent', use_triton=cfg.use_triton)
    model_indep = Mamba3SKALM(cfg_indep).to(device)
    n_indep = sum(p.numel() for p in model_indep.parameters())

    print(f"  Mamba-3 baseline: {n_base:,} params")
    print(f"  SKA-principled:   {n_ska:,} params")
    print(f"  SKA-independent:  {n_indep:,} params")

    # ---- Step 5: Train ----
    print("\n[6/6] Training...")
    all_results = {}
    all_logs = {}

    models = [
        ("Mamba-3", model_base, cfg_base),
        ("SKA-principled", model_ska, cfg_ska),
        ("SKA-independent", model_indep, cfg_indep),
    ]

    for name, model, model_cfg in models:
        print(f"\n{'─' * 50}")
        print(f"Training: {name}")
        print(f"{'─' * 50}")

        torch.manual_seed(42)
        # Re-init weights for fair comparison
        for p in model.parameters():
            if p.dim() > 1:
                nn.init.xavier_uniform_(p)

        logs, best_loss = train(model, train_ds, eval_ds, model_cfg, device)
        all_logs[name] = logs

        # Tool-call evaluation
        print(f"\n  Evaluating tool-calling accuracy...")
        tc_results = evaluate_tool_calling(model, eval_ds, tokenizer, device)
        all_results[name] = tc_results

        print(f"  Function name acc: {tc_results['func_name_acc']:.1%}")
        print(f"  Arguments acc:     {tc_results['args_acc']:.1%}")
        print(f"  Full call acc:     {tc_results['full_acc']:.1%}")

        # Show samples
        for s in tc_results['generated_samples'][:2]:
            print(f"\n  GT:  {s['gt'][:100]}")
            print(f"  Gen: {s['gen'][:100]}")
            print(f"  Match: func={s['func_match']} args={s['args_match']}")

        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    # ---- Comparison ----
    best_model_name = max(all_results, key=lambda k: all_results[k]['full_acc'])
    best_results = all_results[best_model_name]
    best_params = n_ska if 'principled' in best_model_name else n_indep if 'independent' in best_model_name else n_base
    print_comparison(best_results, best_model_name, best_params)

    # ---- Plots ----
    if HAS_MATPLOTLIB:
        fig, axes = plt.subplots(1, 3, figsize=(18, 5))

        # Training loss
        for name, logs in all_logs.items():
            axes[0].plot(logs['step'], logs['train_loss'], label=name)
        axes[0].set_xlabel('Step')
        axes[0].set_ylabel('Train Loss')
        axes[0].set_title('Training Loss')
        axes[0].legend()
        axes[0].grid(True, alpha=0.3)

        # Eval accuracy
        for name, logs in all_logs.items():
            axes[1].plot(logs['step'], logs['eval_acc'], label=name)
        axes[1].set_xlabel('Step')
        axes[1].set_ylabel('Token Accuracy')
        axes[1].set_title('Eval Accuracy')
        axes[1].legend()
        axes[1].grid(True, alpha=0.3)

        # Tool-call comparison bar chart
        model_names = list(all_results.keys())
        func_accs = [all_results[n]['func_name_acc'] for n in model_names]
        args_accs = [all_results[n]['args_acc'] for n in model_names]
        full_accs = [all_results[n]['full_acc'] for n in model_names]

        x = np.arange(len(model_names))
        w = 0.25
        axes[2].bar(x - w, func_accs, w, label='Func Name', color='#2196F3')
        axes[2].bar(x, args_accs, w, label='Args', color='#FF9800')
        axes[2].bar(x + w, full_accs, w, label='Full Call', color='#4CAF50')
        axes[2].set_xticks(x)
        axes[2].set_xticklabels(model_names, rotation=15, ha='right')
        axes[2].set_ylabel('Accuracy')
        axes[2].set_title('Tool-Call Accuracy')
        axes[2].legend()
        axes[2].grid(True, alpha=0.2, axis='y')

        plt.suptitle('SKA v9: 8M-Param Tool-Calling LM', fontsize=14)
        plt.tight_layout()
        plt.savefig('ska_v9_results.png', dpi=150, bbox_inches='tight')
        plt.close()
        print("\nPlot saved to ska_v9_results.png")

    # ---- Throughput comparison ----
    print(f"\n{'=' * 50}")
    print("THROUGHPUT COMPARISON (tokens/sec)")
    print(f"{'=' * 50}")
    for name, logs in all_logs.items():
        if logs['throughput']:
            avg_tput = np.mean(logs['throughput'][-3:])
            print(f"  {name:<25s} {avg_tput:>10,.0f} tok/s")

    return all_results, all_logs


# ---- Synthetic fallback if ToolAlpaca fails to load ----

def _generate_synthetic_tool_data(n_examples):
    """Generate synthetic tool-call examples as fallback."""
    functions = [
        {"name": "search_web", "params": {"query": "str", "max_results": "int"}},
        {"name": "get_weather", "params": {"city": "str", "units": "str"}},
        {"name": "send_email", "params": {"to": "str", "subject": "str", "body": "str"}},
        {"name": "calculate", "params": {"expression": "str"}},
        {"name": "translate", "params": {"text": "str", "target_lang": "str"}},
        {"name": "get_stock_price", "params": {"symbol": "str"}},
        {"name": "set_reminder", "params": {"time": "str", "message": "str"}},
        {"name": "book_flight", "params": {"origin": "str", "dest": "str", "date": "str"}},
    ]

    queries = [
        "What's the weather in {city}?",
        "Search for {topic} and give me the top results",
        "Send an email to {person} about {subject}",
        "Calculate {expr}",
        "Translate '{text}' to {lang}",
        "What's the stock price of {symbol}?",
        "Remind me to {task} at {time}",
        "Book a flight from {origin} to {dest} on {date}",
    ]

    cities = ["Tokyo", "London", "NYC", "Paris", "Berlin"]
    topics = ["machine learning", "climate change", "space exploration"]
    people = ["alice@example.com", "bob@work.org"]
    symbols = ["AAPL", "GOOGL", "TSLA", "MSFT"]

    examples = []
    for _ in range(n_examples):
        func_idx = random.randint(0, len(functions) - 1)
        func = functions[func_idx]

        # Build args
        args = {}
        for p, ptype in func['params'].items():
            if ptype == 'str':
                if p == 'city':
                    args[p] = random.choice(cities)
                elif p == 'query':
                    args[p] = random.choice(topics)
                elif p in ('to',):
                    args[p] = random.choice(people)
                elif p == 'symbol':
                    args[p] = random.choice(symbols)
                else:
                    args[p] = f"sample_{random.randint(1, 100)}"
            elif ptype == 'int':
                args[p] = random.randint(1, 10)

        examples.append({
            'Functions': json.dumps([func]),
            'Instances': json.dumps([{
                'input': f"Please use {func['name']} with appropriate parameters",
                'intermediate_steps': [{'tool': func['name'], 'tool_input': args,
                                        'observation': f"Result: success_{random.randint(1,100)}"}],
                'output': f"I used {func['name']} and got the result for you."
            }])
        })
    return examples


if __name__ == "__main__":
    results, logs = main()
    print("\n✓ SKA v9 complete!")

"""## Run Everything"""

results, logs = main()
print('\n✓ SKA v9 complete!')
